name: "Linux/aarch64 test workflow"

on:
  push:
    branches-ignore:
      - '**-notest'
      - 'upstream-**'
    tags-ignore:
      - '**'

concurrency:
  # An update of a developer branch cancels the previously
  # scheduled workflow run for this branch. However, the default
  # branch, and long-term branch (tarantool-1.10, tarantool-2.8,
  # etc.) workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow
  # run ID' + # 'workflow run attempt' because it is a unique
  # combination for any run. So it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push
  # event.
  group: ${{ (
    github.ref == 'refs/heads/tarantool' ||
    startsWith(github.ref, 'refs/heads/tarantool-')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-luajit:
    runs-on: graviton
    strategy:
      fail-fast: false
      matrix:
        BUILDTYPE: [Debug, Release]
        include:
          - BUILDTYPE: Debug
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=Debug -DLUA_USE_ASSERT=ON -DLUA_USE_APICHECK=ON
          - BUILDTYPE: Release
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
    name: LuaJIT ${{ matrix.BUILDTYPE }} GC64:ON
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: setup
        run: |
          sudo apt -y update
          sudo apt -y install cmake gcc make perl
      - name: configure
        run: cmake . ${{ matrix.CMAKEFLAGS }}
      - name: build
        run: cmake --build . --parallel $(($(nproc) + 1))
      - name: test
        run: cmake --build . --parallel $(($(nproc) + 1)) --target test

  test-tarantool-debug-w-GC64:
    name: Tarantool Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: ON
      buildtype: Debug
      host: graviton
      revision: ${{ github.sha }}
  test-tarantool-release-w-GC64:
    name: Tarantool Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: ON
      buildtype: RelWithDebInfo
      host: graviton
      revision: ${{ github.sha }}
