name: "macOS/x86_64 test workflow"

on:
  push:
    branches-ignore:
      - '**-notest'
      - 'upstream-**'
    tags-ignore:
      - '**'

concurrency:
  # An update of a developer branch cancels the previously
  # scheduled workflow run for this branch. However, the default
  # branch, and long-term branch (tarantool-1.10, tarantool-2.8,
  # etc.) workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow
  # run ID' + # 'workflow run attempt' because it is a unique
  # combination for any run. So it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push
  # event.
  group: ${{ (
    github.ref == 'refs/heads/tarantool' ||
    startsWith(github.ref, 'refs/heads/tarantool-')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-luajit:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        BUILDTYPE: [Debug, Release]
        GC64: [ON, OFF]
        include:
          - BUILDTYPE: Debug
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=Debug -DLUA_USE_ASSERT=ON -DLUA_USE_APICHECK=ON
          - BUILDTYPE: Release
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
    name: LuaJIT ${{ matrix.BUILDTYPE }} GC64:${{ matrix.GC64 }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: setup
        run: |
          # Install brew using the command from Homebrew repository
          # instructions: https://github.com/Homebrew/install.
          # XXX: 'echo' command below is required since brew installation
          # script obliges the one to enter a newline for confirming the
          # installation via Ruby script.
          brew update ||
            echo | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          # Try to install the packages either upgrade it to avoid of fails
          # if the package already exists with the previous version.
          brew install --force cmake gcc make perl ||
            brew upgrade cmake gcc make perl
      - name: configure
        run: cmake . ${{ matrix.CMAKEFLAGS }} -DLUAJIT_ENABLE_GC64=${{ matrix.GC64 }}
      - name: build
        run: cmake --build . --parallel $(($(sysctl -n hw.logicalcpu) + 1))
      - name: test
        run: cmake --build . --parallel $(($(sysctl -n hw.logicalcpu) + 1)) --target test

  test-tarantool-debug-wo-GC64:
    name: Tarantool Debug GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: OFF
      buildtype: Debug
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-debug-w-GC64:
    name: Tarantool Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: ON
      buildtype: Debug
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-release-wo-GC64:
    name: Tarantool Release GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: OFF
      buildtype: RelWithDebInfo
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-release-w-GC64:
    name: Tarantool Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      GC64: ON
      buildtype: RelWithDebInfo
      host: macos-11
      revision: ${{ github.sha }}
