name: Testing

on:
  push:
    branches-ignore:
      - '**-notest'
      - 'upstream-**'
    tags-ignore:
      - '**'

concurrency:
  # An update of a developer branch cancels the previously
  # scheduled workflow run for this branch. However, the default
  # branch, and long-term branch (tarantool-1.10, tarantool-2.8,
  # etc.) workflow runs are never canceled.
  #
  # We use a trick here: define the concurrency group as 'workflow
  # run ID' + # 'workflow run attempt' because it is a unique
  # combination for any run. So it effectively discards grouping.
  #
  # XXX: we cannot use `github.sha` as a unique identifier because
  # pushing a tag may cancel a run that works on a branch push
  # event.
  group: ${{ (
    github.ref == 'refs/heads/tarantool' ||
    startsWith(github.ref, 'refs/heads/tarantool-')) &&
    format('{0}-{1}', github.run_id, github.run_attempt) ||
    format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  test-luajit:
    strategy:
      fail-fast: false
      matrix:
        ARCH: [ARM64, x86_64]
        BUILDTYPE: [Debug, Release]
        GC64: [ON, OFF]
        OS: [Linux, macOS]
        include:
          - ARCH: ARM64
            OS: Linux
            NAME: Linux/aarch64
            RUNNER: graviton
          - ARCH: x86_64
            OS: Linux
            NAME: Linux/x86_64
            RUNNER: ubuntu-20.04-self-hosted
          - ARCH: ARM64
            OS: macOS
            NAME: macOS/M1
            RUNNER: macos-11-m1
          - ARCH: x86_64
            OS: macOS
            NAME: macOS/x86_64
            RUNNER: macos-11
          - BUILDTYPE: Debug
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=Debug -DLUA_USE_ASSERT=ON -DLUA_USE_APICHECK=ON
          - BUILDTYPE: Release
            CMAKEFLAGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
        exclude:
          - ARCH: ARM64
            GC64: OFF
    runs-on: [self-hosted, '${{ matrix.RUNNER }}']
    name: >
      LuaJIT
      (${{ matrix.NAME }})
      ${{ matrix.BUILDTYPE }}
      GC64:${{ matrix.GC64 }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: setup Linux
        uses: ./.github/actions/setup-linux
        if: ${{ matrix.OS == 'Linux' }}
      - name: setup macOS
        uses: ./.github/actions/setup-macos
        if: ${{ matrix.OS == 'macOS' }}
      - name: configure
        run: >
          cmake -S . -B ${{ env.BUILDDIR }}
          -G Ninja
          ${{ matrix.CMAKEFLAGS }}
          -DLUAJIT_ENABLE_GC64=${{ matrix.GC64 }}
      - name: build
        run: cmake --build . --parallel
        working-directory: ${{ env.BUILDDIR }}
      - name: test
        run: cmake --build . --parallel --target test
        working-directory: ${{ env.BUILDDIR }}

  test-tarantool-linux-x86_64-debug-wo-GC64:
    name: Tarantool (Linux/x86_64) Debug GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: ubuntu-20.04-self-hosted
      revision: ${{ github.sha }}
  test-tarantool-linux-x86_64-debug-w-GC64:
    name: Tarantool (Linux/x86_64) Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: ubuntu-20.04-self-hosted
      revision: ${{ github.sha }}
  test-tarantool-linux-x86_64-release-wo-GC64:
    name: Tarantool (Linux/x86_64) Release GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: ubuntu-20.04-self-hosted
      revision: ${{ github.sha }}
  test-tarantool-linux-x86_64-release-w-GC64:
    name: Tarantool (Linux/x86_64) Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: ubuntu-20.04-self-hosted
      revision: ${{ github.sha }}
  test-tarantool-linux-aarch64-debug-w-GC64:
    name: Tarantool (Linux/aarch64) Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: graviton
      revision: ${{ github.sha }}
  test-tarantool-linux-aarch64-release-w-GC64:
    name: Tarantool (Linux/aarch64) Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: graviton
      revision: ${{ github.sha }}
  test-tarantool-macos-x86_64-debug-wo-GC64:
    name: Tarantool (macOS/x86_64) Debug GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-macos-x86_64-debug-w-GC64:
    name: Tarantool (macOS/x86_64) Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-macos-x86_64-release-wo-GC64:
    name: Tarantool (macOS/x86_64) Release GC64:OFF
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: OFF
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-macos-x86_64-release-w-GC64:
    name: Tarantool (macOS/x86_64) Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: macos-11
      revision: ${{ github.sha }}
  test-tarantool-macos-m1-debug-w-GC64:
    name: Tarantool (macOS/M1) Debug GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=Debug
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: Debug
      host: macos-11-m1
      revision: ${{ github.sha }}
  test-tarantool-macos-m1-release-w-GC64:
    name: Tarantool (macOS/M1) Release GC64:ON
    needs: test-luajit
    uses: tarantool/tarantool/.github/workflows/luajit-integration.yml@master
    with:
      CMAKE_EXTRA_PARAMS: >
        -G Ninja
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DLUAJIT_ENABLE_GC64=ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      GC64: ON
      # FIXME: This parameter is obsolete, drop it when
      # CMAKE_EXTRA_PARAMS is activated.
      buildtype: RelWithDebInfo
      host: macos-11-m1
      revision: ${{ github.sha }}
